main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.trips_index, name='index'),
    path('trips/<int:trip_id>/', views.trips_detail, name='detail'),
    path('trips/create/', views.TripCreate.as_view(), name='trips_create'),
    path('trips/<int:pk>/update/', views.TripUpdate.as_view(), name='trips_update'),
    path('trips/<int:pk>/delete/', views.TripDelete.as_view(), name='trips_delete'),
]

tripjournal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.

class Trip(models.Model):
    title = models.CharField(max_length=100)
    from_location = models.CharField(max_length=100)
    to_location = models.CharField(max_length=100)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('detail', kwargs={'trip_id': self.id})

main_app/views.py
from django.http.response import HttpResponse
from django.shortcuts import render
from .models import Trip
from django.views.generic.edit import CreateView, UpdateView, DeleteView

class TripCreate(CreateView):
    model = Trip
    fields = '__all__'

class TripUpdate(UpdateView):
    model = Trip
    fields = '__all__'

class TripDelete(DeleteView):
    model = Trip
    success_url = '/'


# Create your views here.

def trips_index(request):
    trips = Trip.objects.all()
    return render(request, 'home.html', { 'trips': trips })

def trips_detail(request, trip_id):
    trip = Trip.objects.get(id=trip_id)
    return render(request, 'trips/detail.html', { 'trip': trip }) 

main_app/templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabby</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <header id="homeHeader">
          <div id="navHomeSection">
            <a id="navHomeButton" href="/">Tabby</a>
          </div>
          <div id="navOtherSection">
            <div class="navOtherBlock">
              <a class="navOtherButton" href="">
                <p class="navOtherButtonText">Logout</p>
                <div class="navIcon">
                    <img id="navIconImage" src="{% static '/css/main_app/exitIcon.svg' %}" alt="logout Icon">
                </div>
              </a>
              
            </div>
            <div class="navOtherBlock">
              <a class="navOtherButton" href="{% url 'trips_create' %}">
                <p class="navOtherButtonText">Add Trip</p>
                <div class="navIcon">
                    <img id="navIconImage" src="{% static '/css/main_app/Group.svg' %}" alt="Add Icon">
                </div>
              </a>
            </div>
          </div>
        </header>
  
        <div class="generalContent">
          <div class="generalContentHeading">
            <p>My Trip</p>
            <a id="seeMoreButton">See More</a>
          </div>
          <div class="generalContentBlock">
            {% for trip in trips %}
                <a id="tripBlock" href="/trips/{{ trip.id }}">
                    <img id="tripImage" src="{% static '/css/main_app/tokyoFireworks.jpeg' %}">
                    <div class="tripImageShading"></div>
                    <div class="tripContent">
                        <div class="tripDetailBlock">
                        <p id="tripName">{{ trip.title }}</p>
                        <p id="tripUserName">Stevan Johnson</p>
                        </div>
                    </div>
                </a>
            {% endfor %}
          </div>
        </div>

        <div class="generalContent">
            <div class="generalContentHeading">
              <p>Discover Other Trips</p>
              <a id="seeMoreButton">See More</a>
            </div>
            <div class="generalContentBlock">
              {% for trip in trips %}
                  <a id="tripBlock" href="/trips/{{ trip.id }}">
                    <img id="tripImage" src="{% static '/css/main_app/tokyoFireworks.jpeg' %}">
                      <div class="tripImageShading"></div>
                      <div class="tripContent">
                          <div class="tripDetailBlock">
                          <p id="tripName">{{ trip.title }}</p>
                          <p id="tripUserName">Stevan Johnson</p>
                          </div>
                      </div>
                  </a>
              {% endfor %}
            </div>
        </div>
      </main>
</body>
</html>

main_app/templates/main_app/trip_confirm_delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabby</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap" rel="stylesheet">
</head>
<body>
    <main>
        <h1>Delete Trip</h1>

        <h4>Are you sure you want to delete <span class="teal-text">{{ object.title }}</span>?</h4>

        <form action="" method="POST">
            {% csrf_token %}
            <input type="submit" value="Yes - Delete!" class="btn">
            <a href="{% url 'detail' trip.id %}">Cancel</a>
        </form>
    </main>
</body>
</html>

main_app/templates/main_app/trip_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabby</title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap" rel="stylesheet">
</head>
<body>
    <main class="mainform">
        <nav id="formNav">
            <a href="/" class="CRUDButton">
                <div class="formNavIcon">
                    <img id="formNavIconImage" src="{% static '/css/main_app/closeIcon.svg' %}" alt="Close Icon">
                </div>
            </a>
        </nav>
        {% if object %}
        <h1 id="tripTitleDetail">Update Your Trip</h1>
        {% else %}
        <h1 id="tripTitleDetail">Create Your Trip</h1>
        {% endif %}
        <p id="tripUserNameDetail">Add the location and the photos for your trip.</p>
        <div class="formLineBreaker"></div>
        <form action="" method="post" class="formBlock">
            {% csrf_token %}
            <label for="id_title">Title:</label>
            <input type="text" name="title" placeholder="e.g. Tokyo" maxlength="100" required="" id="id_title" class="formInput">
            <div class="inputLine"></div>
            <label for="id_from_location">From location:</label>
            <input type="text" name="from_location" placeholder="e.g. Tokyo" maxlength="100" required="" id="id_from_location" class="formInput">
            <div class="inputLine"></div>
            <label for="id_to_location">To location:</label>
            <input type="text" name="to_location" placeholder="e.g. Tokyo" maxlength="100" required="" id="id_to_location" class="formInput">
            <div class="inputLine"></div>

            <input type="submit" value="Submit!" class="submitButton">
        </form>
    </main>
</body>
</html>


<!--
    <form action="" method="post">
            {% csrf_token %}
            <table>
              {{ form.as_table }}
            </table>
            <input type="submit" value="Submit!" class="btn">
        </form>
-->

main_app/templates/trips/detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabby</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Rubik:wght@300;500;800&display=swap" rel="stylesheet">
</head>
<body>
    <img id="tripImageDetail" src="{% static '/css/main_app/tokyoFireworks.jpeg' %}">
    <nav id="navDetail">
        <nav id="formNav">
            <a href="/" class="CRUDButton">
                <div class="formNavIcon">
                    <img id="formNavIconImage" src="{% static '/css/main_app/closeIcon.svg' %}" alt="Close Icon">
                </div>
            </a>
        </nav>
    </nav>
    <main>
        <header id="headerSectionDetail">
            <div id="headerDetail">
                <h1 id="tripTitleDetail">{{ trip.title }}</h1>
                <p id="tripUserNameDetail">Stevan Johnson</p>
            </div>
            <div id="headerCRUDSection">
                <a href="{% url 'trips_update' trip.id %}" class="CRUDButton">
                <div class="navIcon">
                    <img id="navIconImage" src="{% static '/css/main_app/edit.svg' %}" alt="Add Icon">
                </div>
                </a>
                <a href="{% url 'trips_delete' trip.id %}" class="CRUDButton">
                    <div class="navIcon">
                        <img id="navIconImage" src="{% static '/css/main_app/bin.svg' %}" alt="Add Icon">
                    </div>
                </a>
            </div>
        </header>
        <div class="sectionBreaker"></div>
        <div class="journalHeader">
            <h3 class="diaryEntryHeading">User Diary Entries</h3>
            <a class="navOtherButton" href="">
                <p class="navOtherButtonText">Manage Trip Diary</p>
                <div class="navIcon">
                    <img id="navIconImage" src="{% static '/css/main_app/edit.svg' %}" alt="Add Icon">
                </div>
            </a>
        </div>
        <div id="diaryContentBlock">
            <div class="diaryBlock">
                <p class="diaryBlockText">24th May, 2019</p>
                <p class="diaryBlockText">Lorem ipsum dolor sit amet, 
                    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. 
                </p>
            </div>
            <div class="diaryBlock">
                <p class="diaryBlockText">24th May, 2019</p>
                <p class="diaryBlockText">Lorem ipsum dolor sit amet, 
                    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. 
                </p>
            </div>
        </div>

        <div class="sectionBreaker"></div>
        <div class="journalHeader">
            <h3 class="diaryEntryHeading">Other user comments</h3>
        </div>
        <div id="diaryContentBlock">
            <div class="diaryBlock">
                <p class="diaryBlockText">24th May, 2019</p>
                <p class="diaryBlockText">Lorem ipsum dolor sit amet, 
                    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. 
                </p>
            </div>
            <div class="diaryBlock">
                <p class="diaryBlockText">24th May, 2019</p>
                <p class="diaryBlockText">Lorem ipsum dolor sit amet, 
                    consectetur adipiscing elit, sed do eiusmod tempor incididunt 
                    ut labore et dolore magna aliqua. 
                </p>
            </div>
        </div>


    </main>
</body>
</html>